-- ============================================================================
-- Seeder 001: Default Admin and Member Users
-- Passwords are seeded as bcrypt hashes; plaintext is shown in README.md.
--
-- Admin:   admin@mainkutu.local  /  Admin@12345
-- Member:  member@mainkutu.local /  Member@12345
--
-- IMPORTANT: Both accounts have must_reset_password = 1, so on first login
-- the user is forced to change their password before accessing the system.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Insert default roles
INSERT INTO `roles` (`name`, `slug`, `description`) VALUES
    ('Administrator', 'admin', 'Akaun pentadbir sistem'),
    ('Member',        'member', 'Akaun ahli biasa')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- Insert default admin user
-- password_hash('Admin@12345', PASSWORD_BCRYPT) generated by PHP
-- Hash is recomputed at seed time by PHP for safety; see seed.php.

SET FOREIGN_KEY_CHECKS = 1;
