-- ============================================================================
-- Seeder 001: Default Admin and Member Users
--
-- Demo accounts are created by cron/seed.php at seed time using bcrypt-hashed
-- passwords. Plaintext credentials are intentionally NOT stored in this repo.
--
-- Default accounts (created on first install via the web installer or CLI):
--   - admin@mainkutu.local   (role: admin)
--   - member@mainkutu.local  (role: member)
--
-- IMPORTANT: Both accounts have must_reset_password = 1, so on first login
-- the user is forced to change their password before accessing the system.
-- The installer (install.php) also lets the operator create a real Super
-- Admin account with their own email + password.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Insert default roles
INSERT INTO `roles` (`name`, `slug`, `description`) VALUES
    ('Administrator', 'admin', 'Akaun pentadbir sistem'),
    ('Member',        'member', 'Akaun ahli biasa')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- Insert default admin user
-- password_hash('Admin@12345', PASSWORD_BCRYPT) generated by PHP
-- Hash is recomputed at seed time by PHP for safety; see seed.php.

SET FOREIGN_KEY_CHECKS = 1;
